### ISSUE TITLE
Missing usb_bos_descriptor typedef and defines

### ISSUE THREAD

**Issue by scantoutvite** [devanlai/dapboot#4]
Hi, I want to use dapboot for my project. I fail to see a typedef for the usb_bos_descriptor structure and the  defines used for this structure are missing too. I have looked in the openlibcm3 projects but nothing there either. Can you please direct me to an openlibcm3 which is working with dapboot? Thank you in advance.

Scantoutvite

**Comment by devanlai** [comment]
Hi @scantoutvite,

dapboot currently uses the wcidwebusb branch in my fork of libopencm3, which adds support for the binary object store descriptor for USB 2.1:
https://github.com/devanlai/libopencm3/blob/wcidwebusb/include/libopencm3/usb/usbstd.h#L231

If you cloned the repository recursively, it should have automatically cloned the correct (forked) version of libopencm3. Otherwise you should be able to run `git submodule update --init libopencm3` in your dapboot working copy to fetch it.

**Comment by scantoutvite** [comment]
Hi devanlai,

Got it! Thanks :)

**Comment by scantoutvite** [comment]
Hi Devan Lai,

I have the USB working (STM32F105). I noticed that the VID/PID is 1209/DB42 not the same as the original STM 0483/DF11. I have changed this but the Dfuse software from ST gives me a Bad DFU protocol version. I guess you don’t use the Dfuse software from ST, which software should I use to reprogram my microcontroller?

Thanks,
André (Scantoutvite)

De : Devan Lai [mailto:notifications@github.com]
Envoyé : jeudi 2 novembre 2017 16:41
À : devanlai/dapboot <dapboot@noreply.github.com>
Cc : André RAMAKERS <Andre.RAMAKERS@bea.be>; Mention <mention@noreply.github.com>
Objet : Re: [devanlai/dapboot] Missing usb_bos_descriptor typedef and defines (#4)


Hi @scantoutvite<https://github.com/scantoutvite>,

dapboot currently uses the wcidwebusb branch in my fork of libopencm3, which adds support for the binary object store descriptor for USB 2.1:
https://github.com/devanlai/libopencm3/blob/wcidwebusb/include/libopencm3/usb/usbstd.h#L231

If you cloned the repository recursively, it should have automatically cloned the correct (forked) version of libopencm3. Otherwise you should be able to run git submodule update --init libopencm3 in your dapboot working copy to fetch it.

**Comment by devanlai** [comment]
Hi Andre,
Yes, dapboot implements only the standard DFU 1.1 protocol, not ST's extended DfuSe 1.1a protocol.
If you want a bootloader compatible with ST's tools, there are quite a few DfuSe bootloaders floating around based on the Gareth McMullin's original example DFU code.

I think that the STM32F105 also has a ROM USB DfuSe bootloader, so maybe you don't need to install your own bootloader at all.

For dapboot, I normally use [dfu-util](http://dfu-util.sourceforge.net/) to flash firmware.
If you use Chrome, you can also try out my DFU [webpage](https://devanlai.github.io/webdfu/dfu-util/).

**Comment by scantoutvite** [comment]
Hi Devan Lai,

Thank you for the information. I have tried dfu-util but it doesn’t work. Normally I use the internal boot loader inside the STM 105 but in my product I don’t have access to the boot pin. I have started to change your code for 1.1a, some things already work. If you are interested I can send you the code when I’m finished.

Best regards,
André

Sent from my iPhone

On 7 Nov 2017, at 17:26, Devan Lai <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Andre,
Yes, dapboot implements only the standard DFU 1.1 protocol, not ST's extended DfuSe 1.1a protocol.
If you want a bootloader compatible with ST's tools, there are quite a few DfuSe bootloaders floating around based on the Gareth McMullin's original example DFU code.

I think that the STM32F105 also has a ROM USB DfuSe bootloader, so maybe you don't need to install your own bootloader at all.

For dapboot, I normally use dfu-util<http://dfu-util.sourceforge.net/> to flash firmware.
If you use Chrome, you can also try out my DFU webpage<https://devanlai.github.io/webdfu/dfu-util/>.

**Comment by devanlai** [comment]
Hi Andre,

The dapboot code was actually originally modified from [Gareth's DfuSe code](https://github.com/libopencm3/libopencm3-examples/tree/master/examples/stm32/f1/stm32-h103/usb_dfu) because I preferred the standard DFU behavior where the device accepts an opaque firmware blob - you would probably find it preferable to use the original version ;)

I thought it would be possible to jump to the bootloader address directly, but it seems that the STM32F105/107 series specifically does not list the address for the USB DfuSe bootloader. It might still be possible to locate it by stepping through with a debugger, but I can see why you would want to use a flash bootloader instead.

**Comment by scantoutvite** [comment]
Hi Devan Lai,

Thanks, I’ll get a copy of Gareth’s code.

For the STM32F105 I also use the jump to the bootloader. My problem is when I protect the flash for readout. When this readout protection is removed the flash is automatically erased by the micro itself, just as it should. However after this a reset needs to be issued and after this reset the micro simply tries to start up again from user flash and not from the internal bootloader. Since I don’t have access to the boot pin I need to open the product, connect the boot pin and only then it is possible to inject new software. But I want a solution where I don’t have to open the product. This is why I want to have my own bootloader in user flash and I hope that I can erase and rewrite portions of the user flash with the read protection activated.

The newer STM microcontrollers (STM32F427, STM32F746, but not the STM32F405) work differently. After removing the read protection they always restart on the internal bootloader until new software has been injected.

Best regards,
André

De : Devan Lai [mailto:notifications@github.com]
Envoyé : mardi 7 novembre 2017 19:52
À : devanlai/dapboot <dapboot@noreply.github.com>
Cc : André RAMAKERS <Andre.RAMAKERS@bea.be>; Mention <mention@noreply.github.com>
Objet : Re: [devanlai/dapboot] Missing usb_bos_descriptor typedef and defines (#4)


Hi Andre,

The dapboot code was actually originally modified from Gareth's DfuSe code<https://github.com/libopencm3/libopencm3-examples/tree/master/examples/stm32/f1/stm32-h103/usb_dfu> because I preferred the standard DFU behavior where the device accepts an opaque firmware blob - you would probably find it preferable to use the original version ;)

I thought it would be possible to jump to the bootloader address directly, but it seems that the STM32F105/107 series specifically does not list the address for the USB DfuSe bootloader. It might still be possible to locate it by stepping through with a debugger, but I can see why you would want to use a flash bootloader instead.

**Comment by devanlai** [comment]
Hi Andre,

That makes a lot of sense. Good luck with your project.
