### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by karelbilek** [devanlai/dapboot#5]
Hello

I just want to thank you for this project,

we will be using code from here in bitcoin trezor - https://trezor.io/ , https://github.com/trezor/trezor-mcu

(This is not an issue, just a thanks)

**Comment by devanlai** [comment]
Thanks, I'm glad to hear that you found some part of the code useful - that's why it's open source :).

**Comment by karelbilek** [comment]
See PR here

https://github.com/trezor/trezor-mcu/pull/260
